### PR TITLE
Upgrade to stretch

### PR DESCRIPTION
**Pull request by Ppjet6**
This makes vagrant now use a Debian Stretch image. I updated roles to function with this release.

ATM I commented 4 roles, nihongoparser, sinoparser, suggestd and tatodetect. These should be packaged rather than compiled during the provisioning phase.

### CODE REVIEW

**Comment by jiru** [comment]
About nihongoparserd.
I wrote a [drop-in replacement](/Tatoeba/tatomecab) in Python for this tool, which is easier to maintain, includes a few improvements and tests. We’ve been using it for some time on the previous production server. I never packaged it, so you’d have to take care of this, but you were about to package all our tools anyway. If you have questions about Tatomecab, feel free to ask me.

**Comment by Ppjet6** [comment]
Thanks, I'll have a look. I'm not a fan of Debian packaging but I'll try to come up with something usable.

**Comment by jiru** [comment]
@Ppjet6 There are still some references to the old role `setup_nginx`, which breaks the VM provisioning. I guess you want to rename it into `nginx_base` and eventually add `vhost_tatoeba` where appropriate.

**Comment by jiru** [comment]
I am getting an error because the variable `le_cert_domains` is undefined. Did I miss something?

**Comment by jiru** [comment]
Note to self: set `zend.assertions = 1` in `/etc/php/7.0/fpm/php.ini` so that any failing `assert()` produces a warning when "debug" is set to 1 or 2 in `core.php`.

**Comment by jiru** [comment]
Closing in favor of #40.

**Pull request closed without merging**
